
main: lexer.l parser.y
	bison -d parser.y 
	flex lexer.l 
	gcc parser.tab.c lex.yy.c
	./a.exe <input.txt> output.txt

assembler:
	G:\masm32\bin\ml /c /coff /Cp prog1.asm
	G:\masm32\bin\link -entry:main /subsystem:console prog1.obj
	prog1
	


